[package]
name = "license-retriever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "~1.0.163", features = ["derive"] }
rmp-serde = "~1.1.1"
cargo_metadata = "~0.15.4"
anyhow = { version = "~1.0.71", features = ["backtrace"] }
surf = "~2.3.2"
lazy-regex = "~2.5.0"
itertools = "~0.10.5"
tl = "~0.7.7"
url = "~2.3.1"
futures = "~0.3.28"
log = "~0.4.18"
async-fs = "1.6.0"

[dev-dependencies]
test-log = "~0.2.11"
env_logger = "~0.10.0"
