name: Run cargo-msrv
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@23902aaa9c675b3b4327a80a6c4dabc10f20d723 # main
    permissions:
      contents: write
      pull-requests: write
