name: Run cargo-msrv
on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@152bb7132a819472903318cba5f0bb00bb25dac0 # main
    permissions:
      contents: write
      pull-requests: write
