on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@fa05f9e40a30bb0b0af84e0e462286bbbc8a7f1a # main
    permissions:
      contents: write
      pull-requests: write
