name: Test
on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/mise
        with:
          envs: ''
      - run: cargo test --all-features --all-targets -- --nocapture